### PR TITLE
add xcsrf support to req.py and make it shorter.

### PR DESCRIPTION
**Pull request by iranathan**
this has not been tested.
still adding more ;)

### CODE REVIEW

**Comment by iranathan** [comment]
the `getAllCookies` does nothing I think. 
The request return no cookies 🍪 
```PY
>>> import requests
>>> r = requests.get('https://roblox.com/home')
>>> r.cookies.get_dict()
{}
```

**Comment by iranathan** [comment]
Also, I might need to use a package like bs4 to get join requests. 
As there is not an api for them.

**Comment by iranathan** [comment]
Witch class should `getJoinRequests` be in?

**Comment by sbhadr** [comment]
``Groups_v1 -> Membership`` https://github.com/RbxAPI/Pyblox/blob/nightly_build/pyblox/src/groups.py#L56

**Comment by sbhadr** [comment]
The ``getAllCookies`` method was originally a custom solution to getting cached cookies in order to login instead of manually pasting it into a form-field or JSON. However, support was later dropped due to inconsistencies during retrieval.

**Comment by iranathan** [comment]
It's a cool idea to get the cookie from chrome. but there are problems with this.
If people are using the lib on a server or a vps they will get the error:

`browser_cookie3.BrowserCookieError: Can not find cookie file at: /home/ira/.config/google-chrome/Default/Cookies`

putting this in try except statement will fix this.

**Comment by sbhadr** [comment]
Even if you sign in, there's a chance that it won't find the cookie. I found this to be less-than-optimal.

**Review by sbhadr — APPROVED** [review]

**Comment by sbhadr** [comment]
Sorry that this took so long. Merging.

**Pull request merged**
